### ISSUE TITLE
`ClientConfig::from_kube_config` fails if a cluster with no certificate-authority-data exists

### ISSUE THREAD

**Issue by asthasr** [psFried/roperator#7]
I have a minikube server in my `~/.kube/config` file, specified with paths:

```
- cluster:
    certificate-authority: /Users/myuser/.minikube/ca.crt
    server: https://192.168.99.100:8443
  name: minikube
```

Upon trying to bootstrap a `ClientConfig` with this cluster definition in place, it fails with an error: 

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Format(Message("missing field `certificate-authority-data`", Some(Pos { marker: Marker { index: 4755, line: 16, col: 25 }, path: "clusters[3].cluster" })))', src/libcore/result.rs:1165:5
```
